[SERVERINFO]

VERSION         =   LS.Release.2.0
PACKETVERSION   =   2017110200
CLIENTVERSION   =   JP.R7.983.00

;nome do server
NAME            =   Login Server
GUID            =   10103

PORT            =   10103
IP              =   127.0.0.1


MAXUSER         =   2001

PROPERTY        =   2048

[OPTION]

; 1 ON, 0 OFF
SAME_ID_LOGIN	=	0

; 1 ON, 0 OFF
CREATEUSER		=	0

; 1 SO GM e IP registrados, 0 TODOS
ACCESSFLAG		=	0

; 1 SERVER MANUTENTION, 0 SERVER ONLINE
MANUTENTION = 0

;TTL = Time To Live, tempo em millisegundos para derrubar o player se ele n�o madar a resposta nesse tempo
; ou 0 para desativar
TTL = 60000

ANTIBOTTTL = 10000
[LOG]
DIR 		= Log

[NORMAL_DB]


DBENGINE	=  MSSQL
DBIP		=  pangya_ip
DBNAME		=  pangya_db
DBUSER		=  pangya_user
DBPASS		=  pangya_pass
DBPORT		=  1533
DBLOG		=  0


[AUTHSERVER]

IP		= 127.0.0.1
PORT	= 7777
