[SERVERINFO]

VERSION         =   AS.Release.2.0
PACKETVERSION   =   2024100800
CLIENTVERSION   =   JP.R7.983.01

;nome do server
NAME            =   Auth Server
GUID            =   8888

PORT            =   7777
#nunca deixe isso online, NUNCA !
IP              =   127.0.0.1


MAXUSER         =   100

[OPTION]
 
;TTL = Time To Live, tempo em millisegundos para derrubar o player se ele n�o madar a resposta nesse tempo
; ou 0 para desativar
TTL = 60000 
[LOG]
DIR 		= Log

[NORMAL_DB]

DBENGINE	=  MSSQL
DBIP		=  pangya_ip
DBNAME		=  pangya_db
DBUSER		=  pangya_user
DBPASS		=  pangya_pass
DBPORT		=  1533
DBLOG		=  1