namespace Pangya_GameServer.PangyaEnums
{

    public enum enLEVEL : short
    {
        ROOKIE_F, ROOKIE_E, ROOKIE_D, ROOKIE_C, ROOKIE_B, ROOKIE_A,
        BEGINNER_E, BEGINNER_D, BEGINNER_C, BEGINNER_B, BEGINNER_A,
        JUNIOR_E, JUNIOR_D, JUNIOR_C, JUNIOR_B, JUNIOR_A,
        SENIOR_E, SENIOR_D, SENIOR_C, SENIOR_B, SENIOR_A,
        AMADOR_E, AMADOR_D, AMADOR_C, AMADOR_B, AMADOR_A,
        SEMI_PRO_E, SEMI_PRO_D, SEMI_PRO_C, SEMI_PRO_B, SEMI_PRO_A,
        PRO_E, PRO_D, PRO_C, PRO_B, PRO_A,
        NACIONAL_E, NACIONAL_D, NACIONAL_C, NACIONAL_B, NACIONAL_A,
        WORLD_PRO_E, WORLD_PRO_D, WORLD_PRO_C, WORLD_PRO_B, WORLD_PRO_A,
        MESTRE_E, MESTRE_D, MESTRE_C, MESTRE_B, MESTRE_A,
        TOP_MASTER_V, TOP_MASTER_IV, TOP_MASTER_III, TOP_MASTER_II, TOP_MASTER_I,
        WORLD_MASTER_V, WORLD_MASTER_IV, WORLD_MASTER_III, WORLD_MASTER_II, WORLD_MASTER_I,
        LEGEND_V, LEGEND_IV, LEGEND_III, LEGEND_II, LEGEND_I,
        INFINIT_LEGEND_V, INFINIT_LEGEND_IV, INFINIT_LEGEND_III, INFINIT_LEGEND_II, INFINIT_LEGEND_I
    }
}
